name: Continous Integration

on:
  push:
    branches:
      - '*'
    tags:
      - '*'
    paths-ignore:
      - 'History.md'
      - 'README.md'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        libvips: ["8.10.6", "8.11.4", "8.12.1"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build test-executor
        run: docker build -t h2non/bimg:ci-${{ matrix.libvips }} --build-arg LIBVIPS_VERSION=${{ matrix.libvips }} .
      - name: Run tests
        run: docker run --rm -v $PWD:/go/src/app h2non/bimg:ci-${{ matrix.libvips }} sh -c 'go vet . && golangci-lint run && go test -v -race -covermode=atomic -coverprofile=coverage.out'
